parameters:
    image_size: 512
    total_steps: 100
    learning_rate: 0.05
    alpha: 1000000
    beta: 100

path:
    folder_img_original: "C:\\Users\\aless\\Documents\\03_git_hub_personale\\01_transfer_style\\immagini\\immagini_originali"
    folder_img_style: "C:\\Users\\aless\\Documents\\03_git_hub_personale\\01_transfer_style\\immagini\\immagini_stile"
    folder_img_generated: "C:\\Users\\aless\\Documents\\03_git_hub_personale\\01_transfer_style\\immagini\\immagini_generate"
    name_img_original: "dancing.jpg"
    name_img_style: "picasso.jpg"
    name_img_generated: "dancing_picasso.jpg"